name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    name: Deploy to GFE STG
    runs-on: self-hosted
    environment: production
    
    steps:
      - uses: actions/checkout@v3
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.GFE }}
            HOSTNAME: 34.233.161.125
            USER_NAME: ubuntu
      
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no  -i private_key ubuntu@34.233.161.125 '
              cd /var/www/html/test_new_proj/ &&
              git pull origin main 
              '
